USE DOAN_CNPM
---------------BOOK-----------------------
GO  --DROP PROC USP_UPDATE_BOOK
CREATE PROC USP_UPDATE_BOOK
@ID_BOOK int,@TITLE nchar(300), @AUTHOR nchar(300),@ID_CATEGORY int,
@PUBLISH_YEAR nchar(10),
@PDF_LINK nchar(300),
@OVERVIEW ntext, 
@COVER varbinary(MAX)
AS
BEGIN
UPDATE BOOK
SET TITLE  =@TITLE ,
    AUTHOR =@AUTHOR,
	ID_CATEGOGY= @ID_CATEGORY,
	PUBLISH_YEAR=@PUBLISH_YEAR,
	PDF_LINK =@PDF_LINK,
	OVERVIEW=@OVERVIEW,
	COVER=@COVER
where ID_BOOK = @ID_BOOK
END