//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_CNPM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT_DETAIL()
        {
            this.BOOKMARKs = new HashSet<BOOKMARK>();
            this.SUPPORTs = new HashSet<SUPPORT>();
            this.USER_REVIEW = new HashSet<USER_REVIEW>();
        }
    
        public int ID_ACCOUNT { get; set; }
        public string USER_NAME { get; set; }
        public string PHONENUMBER { get; set; }
        public Nullable<System.DateTime> D_O_B { get; set; }
        public string GENDER { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKMARK> BOOKMARKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPORT> SUPPORTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_REVIEW> USER_REVIEW { get; set; }
    }
}
